name: story_view
description: Display stories just like Whatsapp & Instagram. Can be used inline/inside ListView or Column just like Google News app. Comes with gestures to pause, forward & go to previous page.
version: 0.17.1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  rxdart: ^0.28.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.8.0